/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVolatilityContract {
    function init() external;

    function index() external view returns (uint256);

    function lastVolatility() external view returns (uint256);

    function setVolatility(uint256 new_volatility) external;

    function addSwap(uint256 swap) external;

    function simulateSwap(uint256 swap) external returns (uint256);

    function sqrt(uint256 value) external view returns (uint256);
}